config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  devise_for :admins
  resources :products do
    resource :buy_now , only: [:show, :create], controller: :buy_now do
      get "success" , on: :collection
    end
  end

  resource :cart, only: [:show , :destroy , :create, :update] do
    get "checkout", on: :collection , to: "carts#checkout"
    post "stripe-session", on: :member , to: "carts#stripe_session"
    get "success", on: :member , to: "carts#success"
  end
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "products#index"
end

app/views/admin/show.html.erb
<h1 class="text-5xl font-bold text-center font-miroles mb-8">Admin Dashboard</h1>
<div class="flex justify-center space-x-4">
    <%= link_to "Create New Product", new_product_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded shadow-md" %>
    <%= link_to "Create New Category", new_category_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-6 rounded shadow-md" %>
    <%= link_to "View Products", products_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-6 rounded shadow-md" %>
</div>