config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  devise_for :admins
  resources :products do
    resource :buy_now , only: [:show, :create], controller: :buy_now do
      get "success" , on: :collection
    end
  end

  resource :cart, only: [:show , :destroy , :create, :update] do
    get "checkout", on: :collection , to: "carts#checkout"
    post "stripe-session", on: :member , to: "carts#stripe_session"
    get "success", on: :member , to: "carts#success"
  end
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "products#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user , optional: true
    has_many :cart_items, dependent: :destroy
    has_many :products, through: :cart_items

    before_create :set_secret_id


    enum :status, ["pending", "complete"]


    private 
    def set_secret_id
        self.secret_id = SecureRandom.uuid + DateTime.now.to_i.to_s
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_product, only: [:create, :destroy]
    def create
        if !@current_cart
            @current_cart = Cart.create
            session[:current_cart_id] = @current_cart.secret_id
        end
        
        cart_item = @current_cart.cart_items.find_or_initialize_by(product_id: @product.id)
        cart_item.quantity += cart_item.new_record? ? 0 : 1
        cart_item.save
        redirect_back(fallback_location: products_path, notice: "Product added to your cart")
    end



    def update
        @cart_item = @current_cart.cart_items.find(params[:id])
        new_quantity = params[:quantity].to_i
      
        if new_quantity > 0
          @cart_item.update(quantity: new_quantity)
        else
          @cart_item.destroy
        end
      
        redirect_to cart_path(@current_cart), notice: "Cart updated"
    end


    def show
    end 


    def checkout
        if !@current_cart&.cart_items&.any?
            redirect_to root_path, notice: "You dont have any items in cart yet !"
        end
    end


    def destroy
        @cart_item= @current_cart.cart_items.find_by_product_id(@product.id)
        @cart_item.destroy
        redirect_to cart_path(@current_cart)
    end



    def stripe_session
        session = Stripe::Checkout::Session.create({
        ui_mode: 'embedded',
        line_items: @current_cart.cart_items.map do |cart_item|{
            # Provide the exact Price ID (e.g. pr_1234) of the product you want to sell
            price_data: {
              currency: "usd",
              unit_amount: (cart_item.product.price * 100).to_i,
              product_data: {
                name: @current_cart.products.map(&:name).join(", "),
              },
            },
            quantity: cart_item.quantity,
          }
        end,

          shipping_address_collection:{
            allowed_countries: STRIPE_SUPPORTED_COUNTRIES
          },
          
          mode: 'payment',
          return_url: success_cart_url(@current_cart.secret_id),
      })
  
      render json: { clientSecret: session.client_secret } 
    end 

    def success
      if @current_cart.cart_items.any?
        session[:current_cart_id] = nil
    
        @current_cart.cart_items.each do |cart_item|
          if cart_item.product.stock >= cart_item.quantity
            Order.create!(product: cart_item.product, quantity: cart_item.quantity, total_price: cart_item.product.price * cart_item.quantity, user_id: current_user&.id)
            cart_item.product.update(stock: cart_item.product.stock - cart_item.quantity)
          else
            flash[:alert] = "Niet genoeg voorraad voor #{cart_item.product.name}."
            redirect_to cart_path(@current_cart) and return
          end
        end
    
        @purchased_cart = Cart.find_by_secret_id(params[:id])
        redirect_to root_path if !@purchased_cart
      end
    end
    
    

    private
    def set_product
        @product = Product.find(params[:product_id])
      end
end

app/views/carts/checkout.html.erb
<div class=" w-full grid md:grid-cols-2">
    <div class ="w-full flex flex-col items-center md:pt-8">
        <h1 class="font-miroles text-5xl text-black-100 mb-4 text-center"> Your Cart </h1>
        <% if @current_cart&.cart_items&.any? %>
            <% total_items = @current_cart.cart_items.sum(:quantity) %>
            <p> You have <%= total_items %> <%= "item".pluralize(total_items) %> in your cart </p>
            <div class="mx-auto w-full flex flec-col gap-2 ">
            
                <% @current_cart.cart_items.each.with_index do |cart_item, index| %>
                    <div class="flex gap-2 bg-gray-100 p-2 rounded-lg">
                        <span class="p-2 rounded-full bg-gray-500 text-gray-100"> <%= index + 1 %> </span>
                        <p clas=""> <%= cart_item.product.name %> </p>
                        <p class="text-green-500"> <%= number_to_currency(cart_item.product.price * cart_item.quantity) %> </p>
                    </div>                    

                <% end %>
            </div>

        <%else %>
        <p> Your cart is empty , Take a look around ! </p>
        <%= link_to "Shop Now", products_path, class: "bg-gray-500 text-white font-semibold px-4 py-2 rounded-lg" %>
        <%end%>       
    </div>

        <% if @current_cart&.cart_items&.any? %>
            <div data-controller="stripe-checkout" data-stripe-checkout-url-value="<%= stripe_session_cart_path(@current_cart.secret_id) %>"></div>
        <%end%>
</div>
  

app/views/carts/create.turbo_stream.erb
<%= turbo_stream.update "add-to-cart", partial:"products/add_to_cart", locals: {product: @product}  %>
<%= turbo_stream.update "cart", partial: "layouts/cart", locals: {cart: @current_cart}  %>

app/views/carts/show.html.erb
<div class="w-full flex flex-col items-center md:pt-8">
    <div class="flex justify-between w-full items-center">
        <div class=" flex flex-col gap-4 ">        
            <h1 class= "font-miroles text-5xl text-black-100 mb-4 text-center"> Your Cart </h1>
            <% if @current_cart&.cart_items&.any? %>
                <p> You have <%= @current_cart.cart_items.sum(:quantity) %> items in your cart </p>
            <% else %>
                <p> Your cart is empty , Take a look around ! </p>
                <%= link_to "Shop Now", products_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-semibold px-4 py-2 rounded-lg" %>
            <% end %>
        </div>

        <% if @current_cart&.cart_items&.any? %>
            <div class="flex space-x-4">
                <%= link_to "Checkout", checkout_cart_path, class: "rounded-lg font-semibold p-4 text-center text-xl bg-green-600 hover:bg-green-700" %>
                <% if !current_user %>
                    <%= link_to "Sign in to save your cart", new_user_session_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-semibold px-4 py-2 rounded-lg" %>
                <% end %>
             </div>
        <% else %>
            <div class="flex space-x-4">
                <%= content_tag :div, "Checkout", class: "rounded-lg font-semibold p-4 text-center text-xl bg-green-600 brightness-75 cursor-not-allowed" %>
                <% if !current_user %>
                    <%= link_to "Sign in to save your cart", new_user_session_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-semibold px-4 py-2 rounded-lg" %>
                <% end %>
            </div>
      <% end %>
      

    
    </div>
    <div id="products" class="w-full flex flex-col items-center md:pt-8">
        <% if @current_cart&.cart_items&.any? %>
            <% @current_cart.cart_items.each do |cart_item| %>
                <% product = cart_item.product %>
                <%= render "products/product", product: product %>
                
                <div class="flex items-center space-x-4 mt-2">
                    <%= button_to "➖", cart_path(id: cart_item.id, quantity: cart_item.quantity - 1), method: :patch, class: "bg-gray-300 px-2 py-1 rounded-lg" if cart_item.quantity > 1 %>
                    <span class="text-lg"><%= cart_item.quantity %></span>
                    <%= button_to "➕", cart_path(id: cart_item.id, quantity: cart_item.quantity + 1), method: :patch, class: "bg-gray-300 px-2 py-1 rounded-lg" %>
                </div>
            
                <%= link_to "Remove from cart", cart_path(product_id: product.id), method: :delete, class: "p-2 bg-red-500 text-white font-semibold hover:bg-red-600 rounded-lg" , data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            <% end %>
        <% end %>
    </div>


</div>
      
        

app/views/carts/success.html.erb
<div class="w-full flex flex-col items-center md:pt-8">
    <div class="h-[40vh] w-full mb-8 flex flex-col items-center justify-center gap-4 bg-repeat-round" style="background-image: url('<%= asset_path('giphy (1).gif') %>')">
        <h2 class="font-miroles font-semibold text-5xl text-indigo-50 mb-4 text-center"> Thank you for purchasing! </h2>
        <p class="text-xl font-semibold text-black-300"> All of your products will be shipped shortly </p> 
        </div>
    <h1 class="font-miroles text-5xl text-black-100 mb-4 text-center"> <%= @purchased_cart.products.map(&:name).join(", ") %> </h1>
    <div class="mx-auto w-full flex flec-col gap-2 ">

        <% @purchased_cart.products.each.with_index do |product, index| %>
            <div class="flex gap-2 bg-gray-100 p-2 rounded-lg">
                <span class="p-2 rounded-full bg-gray-500 text-gray-100"> <%= index + 1 %> </span>
                <p clas=""> <%= product.name %> </p>
                <p class="text-green-500"> <%= number_to_currency(product.price) %> </p>
            </div>

        <% end %>
    </div>
</div>