config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  devise_for :admins
  resources :products do
    resource :buy_now , only: [:show, :create], controller: :buy_now do
      get "success" , on: :collection
    end
  end

  resource :cart, only: [:show , :destroy , :create, :update] do
    get "checkout", on: :collection , to: "carts#checkout"
    post "stripe-session", on: :member , to: "carts#stripe_session"
    get "success", on: :member , to: "carts#success"
  end
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "products#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_one_attached :image
  has_rich_text :description

  validates :name, presence: true, format: { with: /[a-zA-Z]/, message: "must include at least one letter" }
  validates :description, presence: true
  validate :description_cannot_be_only_numbers

  #custom validation
  def description_cannot_be_only_numbers
    if description.present? && description.to_plain_text.match?(/\A[0-9]+\z/)
      errors.add(:description, "cannot be only numbers")
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_admin_priv, except: ["index", "show"]
  before_action :set_category, only: %i[ show edit update destroy ]


  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :image)
    end
end

app/views/categories/_category.html.erb
<%= link_to category do %>
  <div id="<%= dom_id category %>" class="relative flex items-center justify-center">
    <%= image_tag category.image , class:"w-full h-85 object-cover rounded-lg shadow-lg hover:brightness-75 transition-all duration-250" if category.image.attached? %>
    <p class ="text-lg text-gray-50 absolute text-2xl font-bold"> <%=category.name %> </p>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Categories" %>

  <h1 class=" text-6xl text-center font-mirole ">All categories</h1>

  <div id="categories" class="min-w-full md:grid grid-cols-4 gap-8">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto w-full flex-col">  
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    
    
    <div class="relative flex items-center justify-center">
      <%= image_tag(@category.image, class: "h-80 w-3/4 mx-auto object-cobver rounded-lg brightness-75") if @category.image.attached? %>
      <h1 class=" text-6xl  text-center font-mirole text-gray-200 absolute "><%= @category.name %> </h1>
    </div>
    <div class="text-xl font-semibold text-gray-500 flex justify-center mt-4">
    <%=@category.description %>
    </div>

    <div id="products" class="min-w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <% @category.products.each do |product| %>
      <%= render "products/product", product: product %>
    
    <% end %>
    </div>

    <% if current_admin %>
      <div class="w-full flex justify-center items-center mt-16 gap-4">
        <%= link_to "Edit this category", edit_category_path(@category), class: " rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <div class="inline-block ml-2">
          <%= button_to "Destroy this category", @category, method: :delete, class: " rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
        </div>
      </div>
    <% end %>
  
</div>